# Generated by Django 4.1.7 on 2023-03-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_samplemodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplemodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
