# Generated by Django 4.1.7 on 2023-03-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('web', 'web'), ('sumaho', 'スマホアプリ'), ('xr', 'XR'), ('game', 'ゲーム'), ('other', 'その他')], max_length=100),
        ),
    ]
